### ISSUE TITLE
update redis refresh & makemap

### ISSUE THREAD

**Issue by raindylong** [kenshinx/godns#26]
https://github.com/raindylong/godns/commit/82f32508a80b1273df8027d756eef2dba4c64055

(1)refresh redis cache when delete some records at redis.
(2)add tmp value to make makemap safety .

**Comment by raindylong** [comment]
@kenshinx ，有空把这个也merge一下如何，主要是两个改动：
（1）用临时变量，避免makemap出现漏空期coredump的危险
（2）之前的写法也并没考虑到如果redis中删除了一个域名，下次refresh的时候，被删除的域名对应关系仍旧会残留在cache中没有被清除

初学，改的不对的话请见谅。

**Comment by kenshinx** [comment]
THX @raindylong 
>（1）用临时变量，避免makemap出现漏空期coredump的危险

确实存在线程不安全的bug，但应该通过读写锁解决，不是你PR中的方法。

> 2）之前的写法也并没考虑到如果redis中删除了一个域名，下次refresh的时候，被删除的域名对应关系仍旧会残留在cache中没有被清除

已修复

**Comment by raindylong** [comment]
收到，谢谢。
