### ISSUE TITLE
i/o timeout

### ISSUE THREAD

**Issue by whutlee** [kenshinx/godns#33]
**Version = "0.1.2"
go version go1.7.4 windows/amd64
nameserver 114.114.114.114**

when query some domain  at same time  “read udp   i/o timeout” randomly occurred,
but use nslookup with host 114.114.114.114 can get the right result.

**Comment by kenshinx** [comment]
I think this problem most possibly be caused by the network lag that from your network to 114.114.114.114. You can try  increment the timeout to mitigate the problem, https://github.com/kenshinx/godns/blob/master/etc/godns.conf#L19

Thanks
