### ISSUE TITLE
使用Redis，没有初始化godns:hosts的key

### ISSUE THREAD

**Issue by wheniworking** [kenshinx/godns#35]
第一次运行，出现以下WARN
2018/01/25 10:18:38 [WARN] Update hosts records from redis failed Redis Error: Key `godns:hosts` does not exist
如果该key不存在，就初始化该Key到Redis。

**Comment by kenshinx** [comment]
并没有觉得设置一个空hashmap有什么必要啊，如果仅仅是不希望有大量warning日志，可以在配置文件中，将[redis-enable 设置为false](https://github.com/kenshinx/godns/blob/master/godns.conf#L50)
