### ISSUE TITLE
打搅了，不知有无计划增加forwarder功能

### ISSUE THREAD

**Issue by raindylong** [kenshinx/godns#36]
Hello @kenshinx,
对标传统的bind的forwarder功能，实际应用中还是比较多的场景需要用到，例如上游某台dns是由另外一个部门维护的，所有的*.abc.local都是由这台上游dns解释，这个场景就需要用到forwarder功能了。

谢谢。

**Comment by kenshinx** [comment]
这是一个通用需求，我这一两天就会加上，谢谢。

**Comment by kenshinx** [comment]
这个功能已经在https://github.com/kenshinx/godns/pull/37 实现， 配置方式可以参考 https://github.com/kenshinx/godns/blob/master/etc/server_list.example.conf ，如果还有别的问题，请再打开这个Issue, 谢谢。
