### ISSUE TITLE
能实现域名解析吗？

### ISSUE THREAD

**Issue by godla** [kenshinx/godns#38]
我的意思是我有个域名
用这个程序能解析到特定服务器上吗？
比如：
我有一台公网服务器 server1 架设这个程序 
然后我又买了个域名，domain1
然后在server1上了 配置域名domain1 解析到server2

最后我家里的电脑 home pc 通过域名 能找到这个server2吗？

**Comment by kenshinx** [comment]
你想让domain1解析到server2，还是仅仅从你家里访问domain1的时候解析到server2？

**Comment by godla** [comment]
domain1解析到server2
公网解析

**Comment by godla** [comment]
我是不是只要在域名的dns 服务器里面填写自己 dns 服务器地址就可以了？

**Comment by kenshinx** [comment]
你需要的是一个nameserver，可以通过两种方式实现
1. 使用公共的DNS服务器，例如dnspod, cloudflare, 有一些域名注册商本身也提供DNS解析服务，例如godaddy
2. 自己架设nameserver，可以使用类似Bind这样的软件

如果仅仅是让域名的解析生效，没什么特殊的需求，第一种更适合你，实际只有很大的公司，有很多域名需要管理，才会选择自己假设nameserver。

**Comment by godla** [comment]
非常感谢你的回答，对我很有帮助
